CREATE OR REPLACE VIEW V1 AS
  SELECT V_VILLA.VILLAID,V_VILLA.OWNER
  FROM (SELECT UNIQUE VILLAID
            FROM V_RESERVATION
            WHERE  TO_DATE('08/15/2014','MM/DD/YYYY') 
            BETWEEN STARTDATE AND ENDDATE)T,V_VILLA
  WHERE T.VILLAID=V_VILLA.VILLAID;

CREATE OR REPLACE VIEW V2 AS           
  SELECT V_USER.ID,COUNT(*) AS UNUSED_VILLA
  FROM V_USER, (SELECT UNIQUE V_VILLA.VILLAID,V_VILLA.OWNER 
                    FROM V_VILLA,V1 
                    WHERE V_VILLA.VILLAID NOT IN (SELECT V1.VILLAID FROM V1))T1
  WHERE V_USER.ID=T1.OWNER
  GROUP BY V_USER.ID;
SELECT * FROM V2;
       

CREATE OR REPLACE VIEW V3 AS
  SELECT COUNT(*) AS TOTAL_COUNT,V_USER.ID FROM V_USER,V_VILLA
  WHERE V_USER.ID=V_VILLA.OWNER
  GROUP BY V_USER.ID;
SELECT * FROM V3;
         
SELECT V2.ID,V2.UNUSED_VILLA/V3.TOTAL_COUNT AS RATIO FROM V2,V3
WHERE V2.ID=V3.ID;
          
